//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.NewsModel {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblNewsId;
		protected global::System.Web.UI.WebControls.TextBox txtNewsType;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtSubTitle;
		protected global::System.Web.UI.WebControls.TextBox txtBrief;
		protected global::System.Web.UI.WebControls.TextBox txtContent;
		protected global::System.Web.UI.WebControls.TextBox txtSmallImageUrl;
		protected global::System.Web.UI.WebControls.TextBox txtAuthor;
		protected global::System.Web.UI.WebControls.TextBox txtFrom;
		protected global::System.Web.UI.WebControls.TextBox txtVideoUrl;
		protected global::System.Web.UI.WebControls.TextBox txtImageUrl;
		protected global::System.Web.UI.WebControls.TextBox txtProductId;
		protected global::System.Web.UI.WebControls.TextBox txtInsertTime;
		protected global::System.Web.UI.WebControls.TextBox txtModifyTime;
		protected global::System.Web.UI.WebControls.TextBox txtTags;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
