//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.NewsModel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblNewsId;
	protected global::System.Web.UI.WebControls.Label lblNewsType;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblSubTitle;
	protected global::System.Web.UI.WebControls.Label lblBrief;
	protected global::System.Web.UI.WebControls.Label lblContent;
	protected global::System.Web.UI.WebControls.Label lblSmallImageUrl;
	protected global::System.Web.UI.WebControls.Label lblAuthor;
	protected global::System.Web.UI.WebControls.Label lblFrom;
	protected global::System.Web.UI.WebControls.Label lblVideoUrl;
	protected global::System.Web.UI.WebControls.Label lblImageUrl;
	protected global::System.Web.UI.WebControls.Label lblProductId;
	protected global::System.Web.UI.WebControls.Label lblInsertTime;
	protected global::System.Web.UI.WebControls.Label lblModifyTime;
	protected global::System.Web.UI.WebControls.Label lblTags;

    }
}
