//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.UserManager.Web.Favorite {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
		protected global::System.Web.UI.WebControls.TextBox txtFavoriteId;
		protected global::System.Web.UI.WebControls.TextBox txtFavoriteUrl;
		protected global::System.Web.UI.WebControls.TextBox txtFavoriteName;
		protected global::System.Web.UI.WebControls.TextBox txtInsertTime;
		protected global::System.Web.UI.WebControls.TextBox txtContentId;
		protected global::System.Web.UI.WebControls.TextBox txtContentType;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new NoName.NetShop.UserManager.Web.MasterPage Master {
            get {
                return ((NoName.NetShop.UserManager.Web.MasterPage)(base.Master));
            }
        }
    }
}
