//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.AddressModel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserId;
	protected global::System.Web.UI.WebControls.Label lblAddressId;
	protected global::System.Web.UI.WebControls.Label lblProvince;
	protected global::System.Web.UI.WebControls.Label lblCity;
	protected global::System.Web.UI.WebControls.Label lblAddressDetail;
	protected global::System.Web.UI.WebControls.Label lblRecieverName;
	protected global::System.Web.UI.WebControls.Label lblMobile;
	protected global::System.Web.UI.WebControls.Label lblTelephone;
	protected global::System.Web.UI.WebControls.Label lblPostalcode;
	protected global::System.Web.UI.WebControls.CheckBox chkIsDefault;
	protected global::System.Web.UI.WebControls.Label lblInsertTime;
	protected global::System.Web.UI.WebControls.Label lblModifyTime;

    }
}
