//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.ProductModel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblProductId;
	protected global::System.Web.UI.WebControls.Label lblProductName;
	protected global::System.Web.UI.WebControls.Label lblProductCode;
	protected global::System.Web.UI.WebControls.Label lblCatePath;
	protected global::System.Web.UI.WebControls.Label lblCateId;
	protected global::System.Web.UI.WebControls.Label lblTradePrice;
	protected global::System.Web.UI.WebControls.Label lblMerchantPrice;
	protected global::System.Web.UI.WebControls.Label lblReducePrice;
	protected global::System.Web.UI.WebControls.Label lblStock;
	protected global::System.Web.UI.WebControls.Label lblSmallImage;
	protected global::System.Web.UI.WebControls.Label lblMediumImage;
	protected global::System.Web.UI.WebControls.Label lblLargeImage;
	protected global::System.Web.UI.WebControls.Label lblKeywords;
	protected global::System.Web.UI.WebControls.Label lblBrief;
	protected global::System.Web.UI.WebControls.Label lblPageView;
	protected global::System.Web.UI.WebControls.Label lblInsertTime;
	protected global::System.Web.UI.WebControls.Label lblChangeTime;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblSortValue;
	protected global::System.Web.UI.WebControls.Label lblScore;

    }
}
