//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.OrderModel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserId;
	protected global::System.Web.UI.WebControls.Label lblOrderId;
	protected global::System.Web.UI.WebControls.Label lblOrderStatus;
	protected global::System.Web.UI.WebControls.Label lblPayMethod;
	protected global::System.Web.UI.WebControls.Label lblShipMethod;
	protected global::System.Web.UI.WebControls.Label lblPayStatus;
	protected global::System.Web.UI.WebControls.Label lblPaysum;
	protected global::System.Web.UI.WebControls.Label lblShipFee;
	protected global::System.Web.UI.WebControls.Label lblProductFee;
	protected global::System.Web.UI.WebControls.Label lblDerateFee;
	protected global::System.Web.UI.WebControls.Label lblAddressId;
	protected global::System.Web.UI.WebControls.Label lblRecieverName;
	protected global::System.Web.UI.WebControls.Label lblRecieverEmail;
	protected global::System.Web.UI.WebControls.Label lblRecieverPhone;
	protected global::System.Web.UI.WebControls.Label lblPostalcode;
	protected global::System.Web.UI.WebControls.Label lblRecieverCity;
	protected global::System.Web.UI.WebControls.Label lblRecieverProvince;
	protected global::System.Web.UI.WebControls.Label lblAddressDetial;
	protected global::System.Web.UI.WebControls.Label lblChangeTime;
	protected global::System.Web.UI.WebControls.Label lblPayTime;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblOrderType;

    }
}
