//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.CategoryParaModel {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblParaId;
		protected global::System.Web.UI.WebControls.TextBox txtCateId;
		protected global::System.Web.UI.WebControls.TextBox txtParaName;
		protected global::System.Web.UI.WebControls.TextBox txtParaType;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtParaGroupId;
		protected global::System.Web.UI.WebControls.TextBox txtParaValues;
		protected global::System.Web.UI.WebControls.TextBox txtDefaultValue;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
