//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.ActionProductModel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblAuctionId;
	protected global::System.Web.UI.WebControls.Label lblProductName;
	protected global::System.Web.UI.WebControls.Label lblSmallIamge;
	protected global::System.Web.UI.WebControls.Label lblMediumImage;
	protected global::System.Web.UI.WebControls.Label lblOutLinkUrl;
	protected global::System.Web.UI.WebControls.Label lblStartPrice;
	protected global::System.Web.UI.WebControls.Label lblAddPrices;
	protected global::System.Web.UI.WebControls.Label lblCurPrice;
	protected global::System.Web.UI.WebControls.Label lblBrief;
	protected global::System.Web.UI.WebControls.Label lblStartTime;
	protected global::System.Web.UI.WebControls.Label lblEndTime;
	protected global::System.Web.UI.WebControls.Label lblStatus;

    }
}
