//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.OrderModel {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
		protected global::System.Web.UI.WebControls.TextBox txtOrderStatus;
		protected global::System.Web.UI.WebControls.TextBox txtPayMethod;
		protected global::System.Web.UI.WebControls.TextBox txtShipMethod;
		protected global::System.Web.UI.WebControls.TextBox txtPayStatus;
		protected global::System.Web.UI.WebControls.TextBox txtPaysum;
		protected global::System.Web.UI.WebControls.TextBox txtShipFee;
		protected global::System.Web.UI.WebControls.TextBox txtProductFee;
		protected global::System.Web.UI.WebControls.TextBox txtDerateFee;
		protected global::System.Web.UI.WebControls.TextBox txtAddressId;
		protected global::System.Web.UI.WebControls.TextBox txtRecieverName;
		protected global::System.Web.UI.WebControls.TextBox txtRecieverEmail;
		protected global::System.Web.UI.WebControls.TextBox txtRecieverPhone;
		protected global::System.Web.UI.WebControls.TextBox txtPostalcode;
		protected global::System.Web.UI.WebControls.TextBox txtRecieverCity;
		protected global::System.Web.UI.WebControls.TextBox txtRecieverProvince;
		protected global::System.Web.UI.WebControls.TextBox txtAddressDetial;
		protected global::System.Web.UI.WebControls.TextBox txtChangeTime;
		protected global::System.Web.UI.WebControls.TextBox txtPayTime;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtOrderType;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
