//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.VoteTopicModel {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblVoteId;
		protected global::System.Web.UI.WebControls.TextBox txtContentId;
		protected global::System.Web.UI.WebControls.TextBox txtContentType;
		protected global::System.Web.UI.WebControls.TextBox txtTopic;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtStartTime;
		protected global::System.Web.UI.WebControls.TextBox txtEndTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsRegUser;
		protected global::System.Web.UI.WebControls.TextBox txtVoteUserNum;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
