//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.AddressModel {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
		protected global::System.Web.UI.WebControls.TextBox txtProvince;
		protected global::System.Web.UI.WebControls.TextBox txtCity;
		protected global::System.Web.UI.WebControls.TextBox txtAddressDetail;
		protected global::System.Web.UI.WebControls.TextBox txtRecieverName;
		protected global::System.Web.UI.WebControls.TextBox txtMobile;
		protected global::System.Web.UI.WebControls.TextBox txtTelephone;
		protected global::System.Web.UI.WebControls.TextBox txtPostalcode;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDefault;
		protected global::System.Web.UI.WebControls.TextBox txtInsertTime;
		protected global::System.Web.UI.WebControls.TextBox txtModifyTime;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
