//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.UserManager.Web.MemberSchool {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluserid;
	protected global::System.Web.UI.WebControls.Label lbltruename;
	protected global::System.Web.UI.WebControls.Label lblduty;
	protected global::System.Web.UI.WebControls.Label lblschool;
	protected global::System.Web.UI.WebControls.Label lblprovince;
	protected global::System.Web.UI.WebControls.Label lblcity;
	protected global::System.Web.UI.WebControls.Label lblcounty;
	protected global::System.Web.UI.WebControls.Label lblMobile;
	protected global::System.Web.UI.WebControls.Label lblTelePhone;
	protected global::System.Web.UI.WebControls.Label lblFax;
	protected global::System.Web.UI.WebControls.Label lblEmail;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new NoName.NetShop.UserManager.Web.MasterPage Master {
            get {
                return ((NoName.NetShop.UserManager.Web.MasterPage)(base.Master));
            }
        }
    }
}
