//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.UserManager.Web.Member {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluserId;
	protected global::System.Web.UI.WebControls.Label lblUserEmail;
	protected global::System.Web.UI.WebControls.Label lblPassword;
	protected global::System.Web.UI.WebControls.Label lblNickName;
	protected global::System.Web.UI.WebControls.Label lblAllScore;
	protected global::System.Web.UI.WebControls.Label lblCurScore;
	protected global::System.Web.UI.WebControls.Label lblLastLogin;
	protected global::System.Web.UI.WebControls.Label lblLoginIP;
	protected global::System.Web.UI.WebControls.Label lblRegisterTime;
	protected global::System.Web.UI.WebControls.Label lblModifyTime;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblstatus;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new NoName.NetShop.UserManager.Web.MasterPage Master {
            get {
                return ((NoName.NetShop.UserManager.Web.MasterPage)(base.Master));
            }
        }
    }
}
