//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.ActionProductModel {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProductName;
		protected global::System.Web.UI.WebControls.TextBox txtSmallIamge;
		protected global::System.Web.UI.WebControls.TextBox txtMediumImage;
		protected global::System.Web.UI.WebControls.TextBox txtOutLinkUrl;
		protected global::System.Web.UI.WebControls.TextBox txtStartPrice;
		protected global::System.Web.UI.WebControls.TextBox txtAddPrices;
		protected global::System.Web.UI.WebControls.TextBox txtCurPrice;
		protected global::System.Web.UI.WebControls.TextBox txtBrief;
		protected global::System.Web.UI.WebControls.TextBox txtStartTime;
		protected global::System.Web.UI.WebControls.TextBox txtEndTime;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
