//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoName.NetShop.Web.VoteGroupModel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblVoteGroupId;
	protected global::System.Web.UI.WebControls.Label lblVoteId;
	protected global::System.Web.UI.WebControls.Label lblGroupType;
	protected global::System.Web.UI.WebControls.Label lblSubject;
	protected global::System.Web.UI.WebControls.Label lblContent;

    }
}
